name: Salesforce CI/CD
on:
  push:
    branches: [develop, main]
    paths:
    - 'force-app/**'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install SFDX CLI
        run: |
          npm install @salesforce/cli --global
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
          sf --version

      - name: 'Installing sfdx git delta'
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Authenticate via JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant \
            --clientid "${{ secrets.SF_CONSUMER_KEY }}" \
            --jwtkeyfile server.key \
            --username "${{ secrets.SF_USERNAME }}"
            
      - name: Generate delta manifest
        run: |
          mkdir changed-sources
          sfdx sgd:source:delta -s force-app --to HEAD --from $GIT_EVENT_BEFORE --output ./changed-sources --generate-delta
          echo "[INFO] Diff generated"

      - name: Run tests & deploy delta
        run: |
          sf project deploy start \
            --manifest delta/package/package.xml \
            --test-level RunLocalTests \
            --target-org targetOrg
