name: Salesforce CI/CD
on:
  push:
    branches: [develop, main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'
            
      # Now Install Salesforce CLI
      - name: Install Salesforce CLI2
        run: |
          npm install @salesforce/cli --location=global
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
          sf --version
      - name: Install sfdx-git-delta2
        run: |
          echo Y | sf plugins install sfdx-git-delta
          sf plugins list

      - name: 'Create delta packages'
        run: | 
            mkdir changed-sources
            sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
            echo "[INFO] Diff generated"

      - name: Authenticate via JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant \
            --clientid "${{ secrets.SF_CONSUMER_KEY }}" \
            --jwtkeyfile server.key \
            --username "${{ secrets.SF_USERNAME }}"
            --set-default            
      - name: 'Deploy to environment with running all local tests'
        run: |
            echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
            sf project deploy start --source-dir changed-sources/force-app --test-level RunLocalTests
