name: Salesforce CI/CD
on:
  pull_request:
    branches: [develop, main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '14'

      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SFDX CLI
        run: npm install sfdx-cli --global

      - name: 'Installing sfdx git delta'
        run: |
          echo y | sfdx plugins:install sfdx-git-delta

      - name: Authenticate via JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant \
            --clientid "${{ secrets.SF_CONSUMER_KEY }}" \
            --jwtkeyfile server.key \
            --username "${{ secrets.SF_USERNAME }}"
            
      - name: Generate delta manifest
        run: |
          mkdir delta
          sf sgd source delta \
            --from "${{ github.sha }}~1" \
            --to "${{ github.sha }}" \
            --output delta \
            --ignore-whitespace \
            -d

      - name: Run tests & deploy delta
        run: |
          sf project deploy start \
            --manifest delta/package/package.xml \
            --test-level RunLocalTests \
            --target-org targetOrg
